### Health Check
GET http://localhost:8080/api/healthcheck

### List
GET http://localhost:8080/api/products?limit=100&order_by=price&order=desc

### Create product
POST http://localhost:8080/api/products
content-type: application/json

{
  "name": "Test product name",
  "description": "Product Description",
  "price": 33500.00,
  "category_id": 1,
  "code": 543,
  "stock": 10
}

### Read product
GET http://localhost:8080/api/products/104


### Update product
PATCH http://localhost:8080/api/products/104
content-type: application/json

{
  "description": "description"
}

### Delete product
DELETE http://localhost:8080/api/products/104

