### Health Check
GET http://localhost:8080/api/healthcheck

### List
GET http://localhost:8080/api/notes

### List
GET http://localhost:8080/api/products?limit=100&order_by=price&order=desc

### Create
POST http://localhost:8080/api/notes
content-type: application/json

{
    "title": "a note 2",
    "content": "here some reminder, mention @raditzlawliet",
    "is_published": true
}




### Create product
POST http://localhost:8080/api/products
content-type: application/json

{
  "name": "Test product name",
  "description": "Product Description",
  "price": 33500.00,
  "category_id": 1,
  "code": 543,
  "stock": 10
}

### Read
GET http://localhost:8080/api/notes/4217276a-60db-40a4-a89b-5583a4786c8d

### Read Product
GET http://localhost:8080/api/products/10

### Update
PATCH http://localhost:8080/api/notes/4217276a-60db-40a4-a89b-5583a4786c8d
content-type: application/json

{
    "content": "here some reminder, mention @raditzlawliet share and like"
}

### Update
PATCH http://localhost:8080/api/products/1
content-type: application/json

{
  "description": "ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы"
}

### Delete
DELETE http://localhost:8080/api/notes/4217276a-60db-40a4-a89b-5583a4786c8d

### Delete product
DELETE http://localhost:8080/api/products/103

